### ISSUE TITLE
Feature: better tree shaking

### ISSUE THREAD

**Issue by elsassph** [lightning-js/renderer#234] opened 2024-04-05 18:20 UTC
Currently Lng3 seem currently quite coupled.

- if we don't use threadx, we shouldn't load the functionality (it is currently always included),
- when canvas renderer will be available, only the right renderer should be loaded.

**Comment by wouterlucas** [comment] 2024-04-08 08:16
Dupe of https://github.com/lightning-js/renderer/issues/160 

Moving it there.

**Closed by wouterlucas** 2024-04-08 08:16 UTC

**Comment by elsassph** [comment] 2024-04-08 08:33
Ok @wouterlucas but the other ticket didn't cover "threadx"

**Comment by wouterlucas** [comment] 2024-04-08 11:38
Fair point, adding it there.
